version: '3'

services:
  #React Application. Assumes sibling directory with Dockerfile
  #
  # 3000:3000 
  #  -> | ->
  react:
    build: ../mtglibrary-react/
    ports:
      - "3000:3000"
    #Maps sibling directory's app to container's app directory
    volumes:
      - '../mtglibrary-react/:/app'
      - '/app/node_modules'
    #Required for react container to resolve spring-boot container hostname
    depends_on:
      - spring-boot
  #Spring Application. Assumes sibling directory with Dockerfile
  #
  # 8080:8080 
  #  -> | ->
  spring-boot:
    build: ../mtglibrary-spring/
    ports:
      - "8080:8080"
    #Required for spring-boot container to resolve elasticsearch container hostname
    depends_on:
      - elasticsearch
  #Single-Node Elasticsearch Cluster. Pulls elasticsearch:7.3.0 from DockerHub 
  #
  # 9300:9300
  #  -> | ->
  elasticsearch:
    image: "elasticsearch:7.3.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    #Required else cluster fails w/ ERR 78
    environment: 
      - discovery.type=single-node

