version: '3'
services:
  spring-boot:
    build: ../mtglibrary-spring/
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
  elasticsearch:
    image: "elasticsearch:7.3.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment: 
      - discovery.type=single-node
